# Crawling Data (Tugas 1)


1.   DATA TWITTER
2.   DATA PTA TRUNOJOYO
3.   DATA BERITA ONLINE

In [ ]:
from bs4 import BeautifulSoup
import requests
URL = "https://pta.trunojoyo.ac.id/c_search/"
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")
results = soup.find(id="content")
#print(results.prettify())

karya_ilmiah_elements = results.find_all(attrs={"data-id": True})

for karya_ilmiah_element in karya_ilmiah_elements:
  judul_element = karya_ilmiah_element.find("a", class_="title")
  abstrak_element = karya_ilmiah_element.find("p")
  print("Judul :",judul_element.text.strip())
  print("Abstrak :",abstrak_element.text.strip())
  print()

In [3]:
import pandas as pd

daf = pd.read_csv("/content/drive/MyDrive/prosaindata/tugas/cleaned_age.csv")
daf.head()

,Unnamed: 0,Unnamed: 0.1,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,66,67,0.133338,0.069304,0.107668,0.089192,0.195267,0.106075,3.043456,13.694173,...,0.133338,0.121968,0.047337,0.277457,0.822656,0.0,4.687500,4.687500,0.076296,young
1,84,85,0.137433,0.058518,0.112037,0.092841,0.200079,0.107238,2.807995,12.776650,...,0.137433,0.111204,0.047151,0.277457,1.313384,0.0,6.046875,6.046875,0.135811,young
2,85,86,0.142227,0.065447,0.112242,0.093455,0.202909,0.109455,2.380899,9.942833,...,0.142227,0.118711,0.047013,0.275862,0.593750,0.0,6.539062,6.539062,0.096102,matured
3,87,88,0.133325,0.072849,0.113360,0.082861,0.203753,0.120892,1.904123,7.799218,...,0.133325,0.116200,0.047105,0.279070,0.424922,0.0,5.812500,5.812500,0.081880,young
4,88,89,0.130487,0.070407,0.113418,0.076098,0.196188,0.120089,1.820873,8.561101,...,0.130487,0.114802,0.047151,0.279070,0.198070,0.0,1.078125,1.078125,0.131579,matured

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive